### ISSUE TITLE
[Bug] FFmpeg acting weird?

### ISSUE THREAD

**Issue by N-SPC700** [nununoisy/gb-presenter-rs#2]
Because the GUI exhibited odd behavior in a previous post I decided to go the command line route. After some fiddling with command line arguments I managed to get it to render:
![image](https://github.com/nununoisy/gb-presenter-rs/assets/38848267/1f268f75-334d-427b-9b4f-47d4153431b7)

That should be the end of it, right? Except I put in the wrong GBS song in the track specifier on accident. Trying to run the command again but with the different (correct) track number produced this:
![image](https://github.com/nununoisy/gb-presenter-rs/assets/38848267/d3c99c31-763d-4fd9-a9a5-9b4a87a18c17)
To ensure the track command itself wasn't buggy I did the original set of commands again (The ones that did render a file) but I unfortunately was met with the same error again:
![image](https://github.com/nununoisy/gb-presenter-rs/assets/38848267/0dc2dcb7-834d-427c-977a-43cc4766cb13)
I'm not sure what is wrong but it seems FFmpeg doesn't like something.

(Side note: The command arguments specified in the repo's readme don't actually match up with the arguments needing to be passed into the program)

I also want to apologize by slamming you with a bunch of issues all of a sudden.

**Comment by N-SPC700** [comment]
Couple extra things to note: 
- Re-rendering works, but I have to specify a different filepath (directory)
- This GBS (I didn't realize this until now) actually does have Japanese characters in it. The GUI doesn't seem to like it but the command line doesn't care.

**Comment by nununoisy** [comment]
First off, I appreciate the prompt reporting on issues. I expect many issues for any first release as people always find usecases I don't consider and bugs/edge-cases pop up.

The "Permission denied" error on Windows is sometimes misleading, since it can also sometimes be thrown when a file is already open in another program. Try deleting the file from Windows Explorer and see if it lets you - if something else has it open chances are you'll be told what program that is. If that's not the case, then I'll have to do a bit more investigation as I can't reproduce this.

**Comment by nununoisy** [comment]
Also, the short flags in the README should work. I'll test and make sure.

**Comment by N-SPC700** [comment]
Alright, cool. I did find the file issue. I had it open in a video program, which is really just my own fault. Closing it since this is just a silly oversight on my end.
